### ISSUE TITLE
Publish extension for Chrome

### ISSUE THREAD

**Issue by thiagoarrais** [anonydog/anonydog#18]
Anonydog has a browser extension that helps people remember to use it by changing the new PR page. It currently is only published in the Firefox store. But it was written using WebExtensions API, which makes it theoretically functional in Chrome also.

We need to verify that the extension really works in Chrome and publish it to the Chrome store.

**Comment by thiagoarrais** [comment]
Hi! Are you a hacktoberfester?
==========

Anonydog welcomes every participant of Hacktoberfest 2017. Just post any questions you may have using the comment box below and I'll get back in touch.

Any questions.

Any.

I mean it.

:blush:

**Comment by brandsjek** [comment]
I will test this in Chrome and make a package and report back.

**Comment by thiagoarrais** [comment]
There is already some ongoing work at #19. Please do test against `chrome-extension`.
