### ISSUE TITLE
Por favor faça um logo para a gente

### ISSUE THREAD

**Issue by thiagoarrais** [anonydog/anonydog#23]
O avatar que o bot usa é de uma foto grátis de catálogo. Seria legal ter um logo para o projeto.

O logo precisa idealmente:

* Lembrar um cachorro
* Lembrar um robô
* Passar a idéia de anonimidade

**Comment by mandyellow** [comment]
espero que goste :-)

![logo-anonydog](https://user-images.githubusercontent.com/30158643/46496025-53afb200-c7ed-11e8-969d-514f3a7642c9.jpg)

**Comment by thiagoarrais** [comment]
Não só gostei como vou mandar tatuar!

**Comment by schirrel** [comment]
GENTE QUE TREM LINDO
